# Generated by Django 4.2 on 2023-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='1994-09-08', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
